### ISSUE TITLE
Flux doesn't support array of component references passed as contructor arg

### ISSUE THREAD

**Issue by grantnd** [ptgoetz/flux#14]
When specifying a component such as **myComponent** in the following config yaml:

``` yaml
- components
  - id: "referencedComponent"
    className: "com.test.Foo"
    ...
  - id: "myComponent"
    className: "com.test.MyClass"
    constructorArgs:
      - [ ref: "referencedComponent" ]
      - "bar"
```

The reference in the list passed as the first contructor arg isn't dereferenced. Then when an attempt is made to instantiate MyClass in **org.apache.storm.flux.FluxBuilder.buildObject**, the first parameter is passed as an ArrayList of LinkedHashMap and an exception is thrown.

I can look at fixing this and making a pull request. Should that be done over in the main Storm project now that Flux is an external?

Alternatively, would you consider Flux providing the option of using Spring as a way to load components? e.g.

``` yaml
components:
   - springDefinition: "/path/to/springDefinition.xml"
```
